# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_access_groups', '0002_fix_group_course_typo_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccourse',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_course', to='course_overviews.CourseOverview'),
        ),
    ]
