# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_access_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='automatic',
            field=models.BooleanField(default=False, help_text='If created by MembershipRule'),
        ),
    ]
