# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 01:34
from __future__ import unicode_literals

import course_access_groups.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_access_groups', '0002_membership_automatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_course', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='membershiprule',
            name='domain',
            field=models.CharField(db_index=True, help_text='The learner email domain e.g. "example.com".', max_length=255, validators=[course_access_groups.validators.validate_domain]),
        ),
    ]
