# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0001_initial'),
        ('course_access_groups', '0003_groupcourse_and_memberrule_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
